Update patch file to include latest changes

diff --git a/package/acme/acme-0100-ssh-deploy-batch-mode.patch b/package/acme/acme-0100-ssh-deploy-batch-mode.patch
--- a/package/acme/acme-0100-ssh-deploy-batch-mode.patch
+++ b/package/acme/acme-0100-ssh-deploy-batch-mode.patch
@@ -1,7 +1,7 @@
 From 3d9608faa086890321ba8d9d630c5b659f89ed46 Mon Sep 17 00:00:00 2001
 From: dkerr64 <david@kerr.net>
 Date: Sat, 22 Feb 2020 20:09:24 -0500
-Subject: [PATCH 1/8] Move -T parameter into default ssh command variable
+Subject: [PATCH 01/11] Move -T parameter into default ssh command variable
 
 ---
  deploy/ssh.sh | 6 +++---
@@ -39,10 +39,65 @@ index 9cb0af9ed..783e6f7b8 100644
  
    if [ "$_ret" != "0" ]; then
 
+From 04771e5a4ae243cdc757b7d3159cef92fce40605 Mon Sep 17 00:00:00 2001
+From: dkerr64 <david@kerr.net>
+Date: Sat, 22 Feb 2020 20:16:36 -0500
+Subject: [PATCH 02/11] Move call to remote system into separate function
+
+---
+ deploy/ssh.sh | 24 +++++++++++++++++-------
+ 1 file changed, 17 insertions(+), 7 deletions(-)
+
+diff --git a/deploy/ssh.sh b/deploy/ssh.sh
+index 783e6f7b8..8c83f0b31 100644
+--- a/deploy/ssh.sh
++++ b/deploy/ssh.sh
+@@ -31,6 +31,7 @@ ssh_deploy() {
+   _ccert="$3"
+   _cca="$4"
+   _cfullchain="$5"
++  _err_code=0
+   _cmdstr=""
+   _homedir='~'
+   _backupprefix="$_homedir/.acme_ssh_deploy/$_cdomain-backup"
+@@ -190,16 +191,25 @@ then rm -rf \"\$fn\"; echo \"Backup \$fn deleted as older than 180 days\"; fi; d
+     _info "Backup directories erased after 180 days."
+   fi
+ 
+-  _secure_debug "Remote commands to execute: " "$_cmdstr"
+-  _info "Submitting sequence of commands to remote server by ssh"
++  if ! _ssh_remote_cmd "$_cmdstr"; then
++    return $_err_code
++  fi
++
++  return 0
++}
++
++#cmd
++_ssh_remote_cmd() {
++  _secure_debug "Remote commands to execute: $_cmd"
++  _info "Submitting sequence of commands to remote server by $Le_Deploy_ssh_cmd"
+   # quotations in bash cmd below intended.  Squash travis spellcheck error
+   # shellcheck disable=SC2029
+-  $Le_Deploy_ssh_cmd "$Le_Deploy_ssh_user@$Le_Deploy_ssh_server" sh -c "'$_cmdstr'"
+-  _ret="$?"
++  $Le_Deploy_ssh_cmd "$Le_Deploy_ssh_user@$Le_Deploy_ssh_server" sh -c "'$_cmd'"
++  _err_code="$?"
+ 
+-  if [ "$_ret" != "0" ]; then
+-    _err "Error code $_ret returned from $Le_Deploy_ssh_cmd"
++  if [ "$_err_code" != "0" ]; then
++    _err "Error code $_err_code returned from $Le_Deploy_ssh_cmd"
+   fi
+ 
+-  return $_ret
++  return $_err_code
+ }
+
 From 6420d1239fda00fb5d40299bfbf1b22c4af4762f Mon Sep 17 00:00:00 2001
 From: dkerr64 <david@kerr.net>
 Date: Sat, 22 Feb 2020 20:31:52 -0500
-Subject: [PATCH 2/8] Move call to remote system into separate function
+Subject: [PATCH 03/11] Move call to remote system into separate function
 
 ---
  deploy/ssh.sh | 25 ++++++++++++++++++-------
@@ -98,7 +153,7 @@ index 783e6f7b8..00d9d21db 100644
 From 283b04df739dff70ed22ee20ffac6a1c576db842 Mon Sep 17 00:00:00 2001
 From: dkerr64 <david@kerr.net>
 Date: Sat, 22 Feb 2020 20:43:28 -0500
-Subject: [PATCH 3/8] Move cleanup of backup directory to first step in the
+Subject: [PATCH 04/11] Move cleanup of backup directory to first step in the
  function.
 
 ---
@@ -151,7 +206,7 @@ index 00d9d21db..39a0a218e 100644
 From cc820e97c6e7cea1d5de0165bd5b7b5d84249843 Mon Sep 17 00:00:00 2001
 From: dkerr64 <david@kerr.net>
 Date: Sat, 22 Feb 2020 21:10:42 -0500
-Subject: [PATCH 4/8] Add support for DEPLOY_SSH_BATCH_MODE with default of
+Subject: [PATCH 05/11] Add support for DEPLOY_SSH_BATCH_MODE with default of
  yes. Before this update all remote commands were bunched together and sent to
  the remote host in a single SSH command.  This could result in a very long
  sequence of commands that might be rejected by a remote host (example is
@@ -295,7 +350,7 @@ index 39a0a218e..92aa43d94 100644
 From 806b746fc0522bed79a1b51f3c0137a0fa721dc5 Mon Sep 17 00:00:00 2001
 From: dkerr64 <david@kerr.net>
 Date: Sat, 22 Feb 2020 21:23:59 -0500
-Subject: [PATCH 5/8] Fix bug where backup and batch_mode yes/no values could
+Subject: [PATCH 06/11] Fix bug where backup and batch_mode yes/no values could
  not be changed. Once set to "no" then they could never be set back to "yes"
 
 ---
@@ -328,7 +383,7 @@ index 92aa43d94..113ae23ef 100644
 From 46ee74ed1687bcc5dbb7732bf7483e6c793ec253 Mon Sep 17 00:00:00 2001
 From: dkerr64 <david@kerr.net>
 Date: Sat, 22 Feb 2020 22:05:06 -0500
-Subject: [PATCH 6/8] Remove variable from info/error printout that could
+Subject: [PATCH 07/11] Remove variable from info/error printout that could
  potentially expose login credentials.
 
 ---
@@ -360,7 +415,7 @@ index 113ae23ef..b68dad7e2 100644
 From f73a49440790018aacff9e1d540c937f481cfc20 Mon Sep 17 00:00:00 2001
 From: dkerr64 <david@kerr.net>
 Date: Sat, 22 Feb 2020 22:09:28 -0500
-Subject: [PATCH 7/8] Remove spaces on blank line to fix travis error
+Subject: [PATCH 08/11] Remove spaces on blank line to fix travis error
 
 ---
  deploy/ssh.sh | 2 +-
@@ -383,7 +438,8 @@ index b68dad7e2..b3e040b34 100644
 From 8ba573d1967e13dcdc03631308f5dbdd3acf565c Mon Sep 17 00:00:00 2001
 From: dkerr64 <david@kerr.net>
 Date: Tue, 3 Mar 2020 13:40:33 -0500
-Subject: [PATCH 8/8] Change variable name to MULTI_CALL so default can be "no"
+Subject: [PATCH 09/11] Change variable name to MULTI_CALL so default can be
+ "no"
 
 ---
  deploy/ssh.sh | 34 +++++++++++++++++-----------------
@@ -494,3 +550,116 @@ index b3e040b34..7eed8a340 100644
    if [ -n "$_cmdstr" ]; then
      if ! _ssh_remote_cmd "$_cmdstr"; then
        return $_err_code
+
+From 554e083f3d387baacbc151b98463efc697091706 Mon Sep 17 00:00:00 2001
+From: dkerr64 <david@kerr.net>
+Date: Wed, 11 Mar 2020 10:58:36 -0400
+Subject: [PATCH 10/11] For MULTI_CALL default to undefined, deleting entry in
+ config file if set to "no"
+
+---
+ deploy/ssh.sh | 16 +++++++++-------
+ 1 file changed, 9 insertions(+), 7 deletions(-)
+
+diff --git a/deploy/ssh.sh b/deploy/ssh.sh
+index 7eed8a340..5d1ee8055 100644
+--- a/deploy/ssh.sh
++++ b/deploy/ssh.sh
+@@ -20,8 +20,8 @@
+ # export DEPLOY_SSH_CAFILE="/etc/stunnel/uca.pem"
+ # export DEPLOY_SSH_FULLCHAIN=""
+ # export DEPLOY_SSH_REMOTE_CMD="/etc/init.d/stunnel.sh restart"
+-# export DEPLOY_SSH_BACKUP=""  # yes or no, default to yes
+-# export DEPLOY_SSH_MULTI_CALL=""  # yes or no, default to no
++# export DEPLOY_SSH_BACKUP=""  # yes or no, default to yes or previously saved value
++# export DEPLOY_SSH_MULTI_CALL=""  # yes or no, default to no or previously saved value
+ #
+ ########  Public functions #####################
+ 
+@@ -76,7 +76,7 @@ ssh_deploy() {
+     Le_Deploy_ssh_cmd="ssh -T"
+   fi
+ 
+-  # BACKUP is optional. If not provided then default to yes
++  # BACKUP is optional. If not provided then default to previously saved value or yes.
+   if [ "$DEPLOY_SSH_BACKUP" = "no" ]; then
+     Le_Deploy_ssh_backup="no"
+   elif [ -z "$Le_Deploy_ssh_backup" ] || [ "$DEPLOY_SSH_BACKUP" = "yes" ]; then
+@@ -84,13 +84,15 @@ ssh_deploy() {
+   fi
+   _savedomainconf Le_Deploy_ssh_backup "$Le_Deploy_ssh_backup"
+ 
+-  # MULTI_CALL is optional. If not provided then default to no
++  # MULTI_CALL is optional. If not provided then default to previously saved
++  # value (which may be undefined... equivalent to "no").
+   if [ "$DEPLOY_SSH_MULTI_CALL" = "yes" ]; then
+     Le_Deploy_ssh_multi_call="yes"
+-  elif [ -z "$Le_Deploy_ssh_multi_call" ] || [ "$DEPLOY_SSH_MULTI_CALL" = "no" ]; then
+-    Le_Deploy_ssh_multi_call="no"
++    _savedomainconf Le_Deploy_ssh_multi_call "$Le_Deploy_ssh_multi_call"
++  elif [ "$DEPLOY_SSH_MULTI_CALL" = "no" ]; then
++    Le_Deploy_ssh_multi_call=""
++    _cleardomainconf Le_Deploy_ssh_multi_call
+   fi
+-  _savedomainconf Le_Deploy_ssh_multi_call "$Le_Deploy_ssh_multi_call"
+ 
+   _info "Deploy certificates to remote server $Le_Deploy_ssh_user@$Le_Deploy_ssh_server"
+   if [ "$Le_Deploy_ssh_multi_call" = "yes" ]; then
+
+From f38df4df1151822d50628be22f27ab3eb20429f4 Mon Sep 17 00:00:00 2001
+From: dkerr64 <david@kerr.net>
+Date: Sat, 14 Mar 2020 21:51:21 -0400
+Subject: [PATCH 11/11] Make remote backup directory path user configurable.
+
+---
+ deploy/ssh.sh | 16 +++++++++++++---
+ 1 file changed, 13 insertions(+), 3 deletions(-)
+
+diff --git a/deploy/ssh.sh b/deploy/ssh.sh
+index 5d1ee8055..d71637a10 100644
+--- a/deploy/ssh.sh
++++ b/deploy/ssh.sh
+@@ -21,6 +21,7 @@
+ # export DEPLOY_SSH_FULLCHAIN=""
+ # export DEPLOY_SSH_REMOTE_CMD="/etc/init.d/stunnel.sh restart"
+ # export DEPLOY_SSH_BACKUP=""  # yes or no, default to yes or previously saved value
++# export DEPLOY_SSH_BACKUP_PATH=".acme_ssh_deploy"  # path on remote system. Defaults to .acme_ssh_deploy
+ # export DEPLOY_SSH_MULTI_CALL=""  # yes or no, default to no or previously saved value
+ #
+ ########  Public functions #####################
+@@ -34,9 +35,8 @@ ssh_deploy() {
+   _cfullchain="$5"
+   _err_code=0
+   _cmdstr=""
+-  _homedir='~'
+-  _backupprefix="$_homedir/.acme_ssh_deploy/$_cdomain-backup"
+-  _backupdir="$_backupprefix-$(_utc_date | tr ' ' '-')"
++  _backupprefix=""
++  _backupdir=""
+ 
+   if [ -f "$DOMAIN_CONF" ]; then
+     # shellcheck disable=SC1090
+@@ -84,6 +84,14 @@ ssh_deploy() {
+   fi
+   _savedomainconf Le_Deploy_ssh_backup "$Le_Deploy_ssh_backup"
+ 
++  # BACKUP_PATH is optional. If not provided then default to previously saved value or .acme_ssh_deploy
++  if [ -n "$DEPLOY_SSH_BACKUP_PATH" ]; then
++    Le_Deploy_ssh_backup_path="$DEPLOY_SSH_BACKUP_PATH"
++  elif [ -z "$Le_Deploy_ssh_backup_path" ]; then
++    Le_Deploy_ssh_backup_path=".acme_ssh_deploy"
++  fi
++  _savedomainconf Le_Deploy_ssh_backup_path "$Le_Deploy_ssh_backup_path"
++
+   # MULTI_CALL is optional. If not provided then default to previously saved
+   # value (which may be undefined... equivalent to "no").
+   if [ "$DEPLOY_SSH_MULTI_CALL" = "yes" ]; then
+@@ -102,6 +110,8 @@ ssh_deploy() {
+   fi
+ 
+   if [ "$Le_Deploy_ssh_backup" = "yes" ]; then
++    _backupprefix="$Le_Deploy_ssh_backup_path/$_cdomain-backup"
++    _backupdir="$_backupprefix-$(_utc_date | tr ' ' '-')"
+     # run cleanup on the backup directory, erase all older
+     # than 180 days (15552000 seconds).
+     _cmdstr="{ now=\"\$(date -u +%s)\"; for fn in $_backupprefix*; \
